# Generated by Django 5.2.4 on 2025-08-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cantact",
            new_name="contact",
        ),
    ]
